### ISSUE TITLE
implementazioni Lunedì 9

### ISSUE THREAD

**Issue by Daniele4ciocchi** [Daniele4ciocchi/JBubbleBobble#1]
## TODO list
- [x] implementazione MVC sul'intero progetto
- [ ] iniziare ad implementare la grafica del primo pannello (classe JBubbleBobble)
- [ ] iniziare ad assegnare ad i character i propri (immagini, non so come spiegarlo)

**Comment by Burnoh** [comment]
sprite

Il giorno lun 9 set 2024 alle ore 11:47 Daniele Quattrociocchi <
***@***.***> ha scritto:
